services:
  db:
    image: postgres:16-alpine
    container_name: compasscar-container
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ${DOCKER_VOLUMES}:/var/lib/postgresql/data
      - ./src/database/init/:/docker-entrypoint-initdb.d/
