version: '3.8'

services:
  compasscar:
    image: postgres:16-alpine
    container_name: compasscar
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compasscar
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - D:/docker/compasscar:/var/lib/postgresql/data
      # Antes do : é o caminho da máquina e depois é o caminho no container
